apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-a
  namespace: argocd
spec:
  destination:
    namespace: python-apps-ns
    server: https://kubernetes.default.svc
  source:
    repoURL: http://host.docker.internal:8082/repository/helm-repo/
    chart: python-app-hc
    targetRevision: 55.0.0
    helm:
      valueFiles:
        - environments/dev/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
