apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-hc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://host.docker.internal:8082/repository/helm-repo/
    chart: python-app-hc
    targetRevision: 55.0.0              # version of the chart
    helm:
      valueFiles:
        - values.yaml                   # optional, if you have inline or remote values
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
