apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        command: ["python"]
        args: ["client.py"]
        env:
        - name: SERVER_HOST
          value: "{{ .Values.client.serverUrl }}"
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-token-secret
              key: API_TOKEN
        - name: POLL_INTERVAL
          value: "{{ .Values.client.pollInterval }}"
        - name: PYTHONUNBUFFERED
          value: "1"          
      {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}          
