apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: {{ .Values.server.service.type }}  # Service type (e.g., NodePort, ClusterIP)
  selector:
    app: server
  ports:
    - protocol: TCP
      port: {{ .Values.server.service.port }}    # The port exposed by the service
      targetPort: {{ .Values.server.port }}      # The port the container listens on
