apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        command: ["python"]
        args: ["server.py"]
        ports:
        - containerPort: {{ .Values.server.port }}
        env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: api-token-secret
              key: API_TOKEN
      {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}              
